### ISSUE TITLE
[Question] Training split data for LOO

### ISSUE THREAD

**Issue by fleskovar** [hamrel-cxu/EnbPI#1]
After reading the paper and looking at the code implementation I still do not understand the validity of the train split for the LOO ensamble and the calculation of the residuals in steps 6 to 10 from the algorithm of the paper.

It seems to me that proposed approach could has leakage from "future" samples into the "past" samples, probably resulting in the residuals of the excluded point from the training set being smaller that what they should be. 

For example, let's say I have 10 samples at different time steps and I exclude sample 8 from the training set. Because this is time series data, points 7 and 9 have some information of point 8, so the resulting model will probably be good at estimating it, resulting in a smaller residual. This might not be the case if the excluded point is the one in place 10, resulting in a bigger residual for this particular case.  Is this correct?

**Comment by hamrel-cxu** [comment]
Thanks for the message. I think this is an interesting hypothesis and would encourage you to examine whether this is the case in reality. Finding a concrete example where this systematically occurs but be really interesting. My impression is that although this is possible, this concept of "some information" is vague so I do not have a good answer. Even if the whole data are generated by an AR process (so there is an analytic form between point 9 and point 10) and we use an AR model to fit the data from a bootstrap sample(e.g., point 8 is used to predict point 9 but point 8 itself is left out), I still do not think the residual should be larger for point 8 than for point 10. The short answer is that the _same_ estimated model is used to predict the value for point 8 and point 10, where the prediction uses points _before_ 8 and 10 as features, respectively. I do not see a clear reason in this case that the prediction should be closer to the actual value of point 8 than to that of point 10.
