### ISSUE TITLE
Question about the Error Update in the Online Case

### ISSUE THREAD

**Issue by WilliamLwj** [hamrel-cxu/EnbPI#2]
Hi Chen,

  I have read your paper and I am curious about Line 16-18 in your algorithm. Could you take a look at the following question?

  Specifically, when you say the set $\epsilon$ gets rid of the first error, and includes the new prediction error (line 18), do you mean the set always removes the first error in terms of time? For example, if $s=1$ and I have $\epsilon = [e_1, e_2, e_3]$ denoting the errors at time 1, 2, 3, and I just got the prediction error for time 4, $e_4$, will it always be the case that $\epsilon$ gets rid of $e_1$ and adds $e_4$ to the list? Like a queue? I am a little confused by your set union notation and what you mean by "reset index of $\epsilon$"

  Thank you so much.

Sincerely,
William

**Comment by hamrel-cxu** [comment]
Hi William, 

I think we met during an earlier meeting and discussed this, so I will close the issue now.
