### ISSUE TITLE
Applications of EnbPI

### ISSUE THREAD

**Issue by datatalking** [hamrel-cxu/EnbPI#3]
How compatible is EnbPI with Natural Language Processing, econometrics or multivariate time series analysis.

This is quite a dense read but I've just read the paper on [Conformal Prediction](http://proceedings.mlr.press/v139/xu21h.html) with unsupervised and supervised sequential anomaly detection, and wanted to ask about applications in other industries.

It is mentioned that "Future work includes several possible directions.. classification problems... computer vision... but also to do more work with anomaly prediction" Its also mentioned that this will be integrated or is being integrated/used with MAPIE, which i'm just learning about today.

**Comment by hamrel-cxu** [comment]
Thanks for your question! I think in essence, EnbPI is designed to provide prediction intervals for any time-series observations, which consist of Y_t (response), X_t (features), f(X_t) (true data function), and \epsilon_t (true errors). How these notations are defined vary across domains so I cannot provide a definitive answer here. I would suggest you to search conformal prediction + X, where X is the application domain you are interested in. I believe EnbPI can always be a plausible alternative for the "conformal part".

Indeed, our work has been integrated in the latest version of [MAPIE](https://github.com/scikit-learn-contrib/MAPIE), which I suggest you take a look. It has various illustrative use cases.
